project:
  type: website
  output-dir: docs

website:
  title: "BIOEST AVANZADA 2023-24"
  navbar:
    left:
      - href: index.qmd
        text: Program
      - href: Chapter1_Exercises.qmd
        text: Chapter 1 - LMM
      # - href: Chapter2_Exercises.qmd
      #   text: Chapter 2 - GLMM

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

